name: Deploy to AWS Elastic Beanstalk

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - run: zip -r my-app.zip . -x "*.git*" "node_modules/*"

      - uses: einaregilsson/beanstalk-deploy@v21
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          application_name: node_simple_api
          environment_name: Nodesimpleapp-env
          region: eu-north-1
          deployment_package: my-app.zip
          wait_for_deployment: true
